### ISSUE TITLE
Localization?

### ISSUE THREAD

**Issue by c0nnex** [jact/openclinic#10]
We localized it according to teh instruction, ic an select the new language but no text is changing.
Also if i switch to one of the default languages, it will do nothing. Basically only english is working.

**Comment by jact** [comment]
What is your operating system? Windows, Linux?

**Comment by c0nnex** [comment]
Linux - Ubuntu

**Comment by jact** [comment]
Look at http://openclinic.sourceforge.net/faq.php [Missing language on Linux system]
